import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import Image from 'next/image';
import './globals.css';
import { IconMenu2 } from '@tabler/icons-react';
import { ThemeProvider } from '@/components/themeProvider';
const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          roboto.className,
          'bg-[#292D39] p-[24px] w-screen overflow-x-hidden'
        )}
      >
        <nav className="flex w-full justify-between items-center shadow-slate-900">
          <div></div>
          <Image src={'/izzat.svg'} alt="IzzatSquad" height={53} width={268} />
          <IconMenu2
            width={30}
            height={30}
            className="text-white cursor-pointer"
          />
        </nav>
        <ThemeProvider>{children}</ThemeProvider>
        <a href="https://api.whatsapp.com/send?l=pt&phone=55011941187901&text=Olá gostaria de tirar dúvidas sobre o Dragrace" target="_blank">
          <Image
            src={'/wppicon.png'}
            alt="Contato"
            height={80}
            width={80}
            className="fixed bottom-[4rem] right-8 cursor-pointer"
          />
        </a>
      </body>
    </html>
  );
}
